### PR TITLE
Pttp 7321

### PR DESCRIPTION
**Pull request by reallydontask**
Inital PR

This repository is used to capture the spokes in the azure landing zone

The objective is for each new spoke to create:

1. A new Project In Azure DevOps
2. A github repository for the spoke
3. A Service Connection for each environment with any relevant roles required as well as API permissions.

The true test will be SFO

Pipeline runs are here:

https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_build?definitionId=130&_a=summary

with a test project

# Note

I will import the existing ones in a separate PR once we have a headless account

Also once we get the headless account the [alz-spokes.tfvars](https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_library?itemType=SecureFiles&view=SecureFileView&secureFileId=dd4bd9c9-7469-4752-a021-61c16747a304&path=alz-spokes.tfvars) file will need to be updated

### CODE REVIEW

**Comment by staff-infrastructure-moj** [comment]
Spoke: Spokes, Environment: Spokes and Pipeline Stage: Spokes
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # github_repository.spoke_repo["staff-infrastructure-testspoke"] will be updated in-place
  ~ resource "github_repository" "spoke_repo" {
      ~ has_projects           = true -> false
        id                     = "staff-infrastructure-testspoke"
        name                   = "staff-infrastructure-testspoke"
        # (26 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

**Comment by staff-infrastructure-moj** [comment]
Spoke: Spokes, Environment: Spokes and Security Scan of Stage: Spokes has failed a IaC security scan, Please look at https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_build/results?buildId=17807&view=ms.vss-test-web.build-test-results-tab

**Comment by staff-infrastructure-moj** [comment]
Spoke: Projects, Environment: Global and Security Scan of Stage: Projects has failed a IaC security scan, Please look at https://dev.azure.com/MoJ-OFFICIAL/Velocity-Landing-Zone/_build/results?buildId=17818&view=ms.vss-test-web.build-test-results-tab

**Review by paulmchenry — APPROVED** [review]
All looks sensible enough 👍

**Pull request merged**
